// Regenerates THIRD_PARTY_NOTICES.md: the license text of every third-party
// package that ships with QuarterDeckLog (the server's production packages and
// everything bundled into the browser code). Run it after any dependency
// change:  npm run generate:notices   (needs `npm ci` run in server/ and web/)
import fs from 'node:fs';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { productionPackages, readPackage } from './npm-tree.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));

// Packages offered under more than one license, and the one we use them under.
const LICENSE_CHOICE = {
  dompurify: 'Apache-2.0 (offered as MPL-2.0 OR Apache-2.0)',
  'expand-template': 'MIT (offered as MIT OR WTFPL)',
  rc: 'MIT (offered as BSD-2-Clause OR MIT OR Apache-2.0)',
};

// For the rare package that declares MIT but ships no license file: the
// standard MIT text, with the copyright holder taken from its package.json.
const MIT_TEXT = (holder) => `MIT License

Copyright (c) ${holder}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.`;

const all = new Map();
for (const part of ['server', 'web']) {
  for (const pkg of productionPackages(`${root}${part}`)) {
    const existing = all.get(pkg.id);
    if (existing) existing.parts.add(part);
    else all.set(pkg.id, { ...pkg, parts: new Set([part]) });
  }
}
// Build tools whose helper code ends up in the browser bundle.
for (const name of ['vite', '@vitejs/plugin-react']) {
  const pkg = readPackage(`${root}web/node_modules/${name}`);
  if (!all.has(pkg.id)) all.set(pkg.id, { ...pkg, parts: new Set(['web']) });
}
const packages = [...all.values()].sort((a, b) => a.id.localeCompare(b.id));

// Group packages that share identical license text so each text appears once.
const groups = new Map();
const noText = [];
for (const pkg of packages) {
  if (pkg.files.length === 0) {
    if (pkg.license === 'MIT' && pkg.author) {
      pkg.files = [{ file: '(generated)', text: MIT_TEXT(pkg.author) }];
    } else {
      noText.push(pkg);
      continue;
    }
  }
  const combined = pkg.files.map((f) => f.text).join('\n\n');
  const key = crypto.createHash('sha256').update(combined).digest('hex');
  if (!groups.has(key)) groups.set(key, { text: combined, packages: [] });
  groups.get(key).packages.push(pkg);
}

const lines = [];
lines.push('# Third-Party Notices');
lines.push('');
lines.push('QuarterDeckLog is released under the MIT License (see LICENSE). It includes or installs the third-party');
lines.push('software listed below. Each package is listed with its license, followed by the license text it is');
lines.push('distributed under. Where a package declares the MIT license but ships no license file, the standard MIT text is');
lines.push('given with the copyright holder named in its package.json. This file is generated by scripts/generate-notices.mjs;');
lines.push('do not edit it by hand.');
lines.push('');
lines.push('SQLite, which is compiled into better-sqlite3, is in the public domain (https://sqlite.org/copyright.html).');
lines.push('');
lines.push(`${packages.length} packages. Server: ${packages.filter((p) => p.parts.has('server')).length}. Browser code: ${packages.filter((p) => p.parts.has('web')).length}.`);
lines.push('');
const choices = packages.filter((p) => LICENSE_CHOICE[p.name]);
if (choices.length) {
  lines.push('## License choices');
  lines.push('');
  for (const p of choices) lines.push(`- ${p.id}: used under ${LICENSE_CHOICE[p.name]}`);
  lines.push('');
}

let n = 0;
for (const group of [...groups.values()].sort((a, b) => a.packages[0].id.localeCompare(b.packages[0].id))) {
  n += 1;
  lines.push('================================================================================');
  lines.push(`## ${n}. Packages under this license text`);
  lines.push('');
  for (const p of group.packages) lines.push(`- ${p.id} (${p.license})${p.repo ? ` - ${p.repo.replace(/^git\+/, '')}` : ''}`);
  lines.push('');
  lines.push(group.text);
  lines.push('');
}
if (noText.length) {
  lines.push('================================================================================');
  lines.push('## Packages that do not include a license file');
  lines.push('');
  lines.push('These packages declare their license in package.json but ship no license text:');
  lines.push('');
  for (const p of noText) lines.push(`- ${p.id}: ${p.license}${p.repo ? ` - ${p.repo.replace(/^git\+/, '')}` : ''}`);
  lines.push('');
}

fs.writeFileSync(`${root}THIRD_PARTY_NOTICES.md`, `${lines.join('\n')}\n`);
console.log(`Wrote THIRD_PARTY_NOTICES.md: ${packages.length} packages, ${groups.size} distinct license texts, ${noText.length} without a license file.`);
const byLicense = {};
for (const p of packages) byLicense[p.license] = (byLicense[p.license] || 0) + 1;
console.log('Licenses:', JSON.stringify(byLicense));
if (noText.length) console.log('No license file:', noText.map((p) => `${p.id} (${p.license})`).join(', '));
